name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: install packages
      run: brew install nasm curl

    - name: x86_64-elf-gcc
      run: brew install x86_64-elf-gcc

    - name: build
      run: make all

  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: install packages
      run: sudo apt install nasm curl

    - name: build
      run: make all

